# -*- mode: ruby -*-
# vi: set ft=ruby :

disk1 = 'disk1.vdi'
disk2 = 'disk2.vdi'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # ###
  config.vm.network "private_network", ip: "192.168.33.11"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "512"

    unless File.exist?(disk1)
      vb.customize ['storagectl', :id, '--name', 'SCSI Controller', '--add', 'scsi', '--portcount', 16]

      vb.customize ['createhd', '--filename', disk1, '--size', 4 * 1024]
    end

    vb.customize ['storageattach', :id, '--storagectl', 'SCSI Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk1]

    unless File.exist?(disk2)
      vb.customize ['createhd', '--filename', disk2, '--size', 4 * 1024]
    end

    vb.customize ['storageattach', :id, '--storagectl', 'SCSI Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk2]

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    export http_proxy=http://proxy.cht.com.tw:8080
    export https_proxy=http://proxy.cht.com.tw:8080

    apt-get update
    apt-get install -y mdadm
    apt-get install -y glusterfs-server

    mdadm --create /dev/md0 --metadata=0.90 --level=mirror --raid-devices=2 /dev/sd[b-c]
    mkfs.ext4 /dev/md0
    mount /dev/md0 /mnt

    echo '/dev/md0 /mnt ext4 defaults 0 0' >> /etc/fstab

    mdadm --detail -scan >> /etc/mdadm/mdadm.conf
    update-initramfs -u
    
  SHELL
end

